config/routes.rb
AdvancedCapybara::Application.routes.draw do
  devise_for :users

  resources :messages

  root :to => "messages#index"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :reply_to_message, :class_name => 'Message'
  validates_presence_of :message, :user_id

  scope :recent, order('created_at DESC').limit(10)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  validates_presence_of :username

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = current_user.messages.build
    respond_to do |format|
      format.js { render :partial => 'messages.html.erb' }
      format.html { render 'index' }
    end
  end

  def new
    @reply_to = Message.find(params[:reply_to]) if params[:reply_to]
    @message = current_user.messages.build
    respond_to do |format|
      format.js { render :partial => 'form.html.erb' }
      format.html { render 'new_reply' }
    end
  end

  def create
    @message = current_user.messages.build(params[:message])

    if @message.save
      respond_to do |format|
        format.js { render :partial => 'messages.html.erb' }
        format.html { render 'index' }
      end
    else
      render "index"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oink</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="page">
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <p><%= f.label :message, 'New message' %></p>
  <p><%= f.text_area :message, :rows => 4 %></p>
  <p>
    <%= f.hidden_field :reply_to_message_id, :value => @reply_to.id if @reply_to %>
    <%= f.submit "Send" %>
  </p>
<% end %>

app/views/messages/_message.html.erb
<h3><%= message.message %></h3>
<p>by <%= message.user.username %></p>
<% if message.reply_to_message %>
  <p><%= link_to "In reply to", "#" + dom_id(message.reply_to_message), :class => 'in-reply-to' %></p>
<% end %>
<p><%= link_to 'Reply', new_message_path(:reply_to => message), :class => 'reply' %></p>

app/views/messages/_messages.html.erb
<ul id="messages">
  <% Message.recent.each do |message| %>
    <%= content_tag_for(:li, message) do %>
      <%= render message %>
    <% end %>
  <% end %>
</ul>

app/views/messages/index.html.erb
<h1>Oink</h1>

<p><%= link_to 'New message', new_message_path, :class => 'new' %></p>

<%= render :partial => 'messages' %>

<%= javascript_include_tag 'messages' %>

app/views/messages/new_reply.html.erb
<h1>Reply to message<h1>

<%= render 'form' %>